openservicemesh/osm-docs

netlify.toml

Adding the original netlify config per @flynnduism.

Adding netlify config

---

README.md

Correcting paths for new repo.

Correcting paths

---

wip/demo_dapr.md

This commit contains the necessary documentation to Integrate OSM with a
Dapr Demo.
Fixes : https://github.com/openservicemesh/osm/issues/2875 

feat(Dapr): Integration with Dapr

---

content/docs/apidocs/_index.md
content/docs/apidocs/policy/_index.md
content/docs/apidocs/policy/v1alpha1.md

Adds _index.md files for the directories to correctly
render the directory structure on the website.

apidocs: Add index.md files to correctly organize docs

---

wip/demo_dapr.md

docs(Dapr) : update namespace for dapr demo

---

content/docs/HA/_index.md
content/docs/design_concepts/osm_components_interactions/_index.md
content/docs/scale/_index.md
wip/demo_dapr.md

Fixing double Headers  
Signed-off-by: Atharva Patil <yatinchaudhari8254@gmail.com>

Fixing Duplicate headers

---

README.md
content/docs/HA/_index.md
content/docs/getting_started/_index.md
content/docs/install/_index.md
content/docs/install/manual_demo/_index.md
content/docs/install/uninstallation_guide.md
content/docs/tasks_usage/namespace_monitoring.md
content/docs/tasks_usage/observability/metrics_manual_guide.md
content/docs/tasks_usage/traffic_management/ingress.md
content/docs/troubleshooting/observability/grafana.md
content/docs/troubleshooting/observability/prometheus.md
content/docs/troubleshooting/upgrade.md
content/docs/upgrade_guide.md

Fixing broken links

---

content/docs/install/_index.md
content/docs/install/uninstallation_guide.md

Fixing a broken link and re-adding one that was removed when it couldn't work both on github and the website.

Adding links

---

content/docs/apidocs/policy/v1alpha1.md

Updates the API references based on the latest changes
made to the API.

apidocs: update policy v1alpha1 api reference

---

content/docs/tasks_usage/traffic_management/demos/egress_policy_demo.md

Documents using HTTP egress with SMI HTTP route matching.
Part of openservicemesh/osm#3045

egress/demo: document HTTP egress with SMI route matching

---

content/docs/install/auto_demo.md

While linking to a raw image out of the source-code github repo isn't ideal, I also don't want to duplicate (versus perhaps/hopefully move), so I will defer the decision.

Fixing broken link

---

content/docs/integrations/_index.md

Adding file as mentioned in https://github.com/openservicemesh/osm-docs/pull/50#issuecomment-842670425

Adding index file for better sorting

---

content/docs/integrations/demo_dapr.md

Reviewing this demo script, we found small typos to correct.

Minor fixes to demo script

---

content/docs/apidocs/config/_index.md
content/docs/apidocs/config/v1alpha1.md

Adding api docs for meshconfig CRD

apidocs: add generated API docs for the meshconfig CRD

---

content/docs/osm_mesh_config.md

meshconfing: add reference to config api docs in meshConfig doc

---

content/docs/application_health_probes.md
content/docs/control_plane_health_probes.md
content/docs/install/manual_demo.md
content/docs/osm_mesh_config.md

Update latest version of docs to v0.8.4
Signed-off-by: Johnson Shi <Johnson.Shi@microsoft.com>

update latest version to v0.8.4

---

config.toml
themes/dosmy/layouts/partials/banner.html

Small adjustments for https://github.com/openservicemesh/osm-docs/issues/67 (we can iterate further in that issue).

Release v0.8 adjust

---

content/docs/install/manual_demo.md

Would like this commit cherry-picked to the release-v0.8 branch if possible.

Added openshift clarification for Manual Demo

---

content/docs/install/manual_demo/_index.md

Signed-off-by: nshankar13 <nshankar@microsoft.com>

Add openshift clarification for manual demo

---

content/docs/install/manual_demo.md

Fixing a few typos and adding a few clarifications. I'm attempting to explain what gets installed and I may have missed something; corrections welcome.

Manual demo clarifications

---

README.md

Notes on how to add and (if necessary) change any release-specific docs. @flynnduism for any clarifications, corrections, additions needed.

Adding and updating release-specific docs

---

content/_index.md
content/docs/design_concepts/_index.md
content/docs/getting_started/auto_demo.md
content/docs/getting_started/demos.md
content/docs/getting_started/manual_demo.md
content/docs/install/_index.md

Signed-off-by: Zach Rhoads <43684271+zr-msft@users.noreply.github.com>
relates to #95

Added demo list and revised install steps

---

config.toml
content/docs/concepts_features/control_plane_health_probes.md
content/docs/concepts_features/high_availability.md
content/docs/concepts_features/osm_mesh_config.md
content/docs/getting_started/manual_demo.md
content/docs/install/_index.md
content/docs/install/troubleshooting.md
content/docs/install/uninstallation_guide.md
content/docs/tasks/certificates.md
content/docs/tasks/health_probes.md
content/docs/tasks/observability/logs.md
content/docs/tasks/observability/metrics.md
content/docs/tasks/observability/metrics_manual_guide.md
content/docs/tasks/observability/tracing.md
content/docs/tasks/onboard_services.md
content/docs/tasks/traffic_management/demos/egress_policy_demo.md
content/docs/tasks/traffic_management/egress.md
content/docs/tasks/traffic_management/ingress.md
content/docs/tasks/traffic_management/iptables_redirection.md
content/docs/tasks/upgrade.md

relates to #108
relates to #106

update references for osm to v0.9

---

content/docs/tasks/observability/logs.md

Signed-off-by: Kalya Subramanian <kasubra@microsoft.com>

Fluent Bit not supported on OpenShift

---

content/docs/install/_index.md

Signed-off-by: Kalya Subramanian <kasubra@microsoft.com>
PodSecurityPolicies are fully supported in 0.9.0

psp: Document full support for PSP

---

content/docs/getting_started/manual_demo.md

 convert inline manifests to versioned links

---

config.toml

Signed-off-by: Zach Rhoads <43684271+zr-msft@users.noreply.github.com>

added ver 0.9

---

content/docs/concepts_features/high_availability.md

Adding the horizontal pod autoscaler and pod disruption budget sections to the HA doc
Signed-off-by: Shalier Xia <shalierxia@microsoft.com>

Updates the HA doc, adding HPA and PDB sections

---

content/docs/apidocs/config/v1alpha1.md

Updates API reference docs for the MeshConfigs. Adds ClusterSpec and FeatureFlags.
Resolves #119
Signed-off-by: Jackie Elliott <jaellio@microsoft.com>

Update api docs for MeshConfig

---

content/docs/tasks/traffic_management/ingress.md

Documents how to ignore an ingress resource.
Part of openservicemesh/osm#3582

ingress: document ignore label

---

content/docs/getting_started/manual_demo.md
content/docs/install/_index.md
content/docs/tasks/traffic_management/ingress.md

 update minimum Kubernetes version to 1.19

---

content/docs/concepts_features/high_availability.md

Noticed some embedded images had broken links.

Fixing links

---

content/docs/tasks/onboard_services.md

Fixes broken reference to the sidecar injection doc.

tasks: fix broken reference

---

content/docs/tasks/onboard_services.md

Fixes broken reference to the sidecar injection doc.

[backport] tasks: fix broken reference

---

content/docs/concepts_features/osm_mesh_config.md
content/docs/install/_index.md
content/docs/tasks/observability/_index.md
content/docs/tasks/onboard_services.md
content/docs/tasks/traffic_management/_index.md
content/docs/tasks/traffic_management/egress.md
content/docs/tasks/traffic_management/troubleshooting/_index.md

Backports 6746df3 and 076d51f to release-v0.9.

[backport]: cherry-pick 6746df3 and 076d51f to release-v0.9

---

content/docs/install/uninstallation_guide.md
content/docs/tasks/upgrade.md

Add information about CRD upgrades to OSM upgrade and uninstall
Part of https://github.com/openservicemesh/osm/issues/3396

feat(crdUpgrades): Add CRD upgrade info

---

content/docs/tasks/external_auth_opa.md

Contains overview of the feature, configuration and example
walkthrough.
Signed-off-by: Eduard Serra <eduser25@gmail.com>

Add external authorization guide

---

content/docs/apidocs/config/v1alpha1.md
content/docs/apidocs/policy/v1alpha1.md

Updates the API reference docs.

apidocs: update API reference docs

---

content/docs/demos/prometheus_grafana.md

Fixing relative references.
Signed-off-by: Eduard Serra <eduser25@gmail.com>

docs: fix image references in prom/grafana byo guide

---

content/docs/getting_started/install.md
content/docs/guides/cli.md

Fixed osm cli link and added download cli instructions for OS installs

Updated cli link and added cli OS installs

---

content/docs/demos/ingress_k8s_nginx.md

Documents demo for HTTP and HTTPS ingress with k8s Nginx
Ingress Controller.

demos: add ingress demo with k8s nginx ingress controller

---

content/docs/getting_started/quickstart/manual_demo.md
content/docs/getting_started/upgrade.md
content/docs/guides/health_checks/control_plane_health_probes.md
content/docs/guides/health_checks/health_probes.md
content/docs/guides/mesh_config.md
content/docs/guides/traffic_management/iptables_redirection.md

chore(release): update osm version to v0.9.2

---

content/docs/guides/app_onboarding/_index.md
content/docs/guides/app_onboarding/app_protocol_selection.md

Documents app protocol selection for service
ports.

docs: document app protocol selection

---

content/docs/getting_started/upgrade.md

Document that cluster requires minimum Kubernetes version for upgraded chart
Signed-off-by: Kalya Subramanian <kasubra@microsoft.com>

docs(upgrade): Require minimum Kubernetes version

---

content/docs/guides/certificates.md

Signed-off-by: nshankar13 <nshankar@microsoft.com>
Add steps on how to rotate the root cert to the certificates.md doc.

docs(certificates): Rotate root cert

---

content/docs/guides/osm_components.md
content/docs/guides/traffic_management/ingress.md

docs: fix small typos

---

content/docs/demos/prometheus_grafana.md
content/docs/getting_started/install.md
content/docs/getting_started/quickstart/manual_demo.md
content/docs/getting_started/upgrade.md
content/docs/guides/app_onboarding/_index.md
content/docs/guides/certificates.md
content/docs/guides/ha_scale/high_availability.md
content/docs/guides/mesh_config.md
content/docs/guides/observability/logs.md
content/docs/guides/observability/metrics.md
content/docs/guides/observability/tracing.md
content/docs/guides/troubleshooting/install.md

Updates the release references to v0.10.
Also removes hardcoded references to line numbers
that are hard to maintain.

docs: update release refs to v0.10

---

content/docs/getting_started/quickstart/manual_demo.md
content/docs/getting_started/upgrade.md
content/docs/guides/health_checks/control_plane_health_probes.md
content/docs/guides/health_checks/health_probes.md
content/docs/guides/mesh_config.md
content/docs/guides/traffic_management/iptables_redirection.md

Updates the version refs for release-v0.10.

docs: update v0.9.2 refs to v0.10.0

---

content/docs/guides/cli.md

Updates the version refs to v0.10.0.

docs: update version ref to v0.10.0

---

config.toml

Adds v0.10 to the release dropdown menu.

config.toml: add v0.10 to the release dropdown menu

---

content/docs/getting_started/uninstall.md
content/docs/getting_started/upgrade.md

Update to the uninstall and upgrade docs on how osm CRDs are managed
during upgrades

Update CRD upgrade process

---

content/docs/getting_started/install.md
content/docs/guides/reconciler.md

Adding documentation on the reconciler feature in OSM
Part of https://github.com/openservicemesh/osm/issues/4065

Add documentation for reconciler

---

content/docs/getting_started/upgrade.md

Add guide for upgrading third party dependencies. 
Signed-off-by: nshankar13 <nshankar@microsoft.com>

docs(upgrade): third party dependencies

---

content/docs/guides/troubleshooting/osm_health.md

Hold until osm-health is ready for use

docs(osm-health): add doc for osm-health

---

content/docs/getting_started/install.md

Part of https://github.com/openservicemesh/osm/issues/4162

Add note on single mesh enforcement

---

config.toml

Updates config.toml for the release-v0.11 specific doc site.

release-v0.11: update config.toml

---

content/docs/demos/prometheus_grafana.md
content/docs/getting_started/install.md
content/docs/getting_started/quickstart/manual_demo.md
content/docs/getting_started/upgrade.md
content/docs/guides/app_onboarding/_index.md
content/docs/guides/certificates.md
content/docs/guides/ha_scale/high_availability.md
content/docs/guides/mesh_config.md
content/docs/guides/observability/logs.md
content/docs/guides/observability/metrics.md
content/docs/guides/observability/tracing.md
content/docs/guides/troubleshooting/install.md

Updates the release references to v0.11. Also removes hardcoded
references to line numbers that are hard to maintain (#186).

release-v0.11: update release refs to v0.11

---

resources/_gen/assets/scss/scss/main.scss_4deeccf10f3562b4fc3bf03d70e042fd.content
themes/dosmy/assets/scss/main.scss

Signed-off-by: nshankar13 <nshankar@microsoft.com>

Modify sidebar list icon

---

content/docs/guides/uninstall.md

guides(uninstall): fix broken links

---

content/docs/guides/osm_resource_limits.md

Adds documentation for resource requests and limits of OSM pods and deployments
Signed-off-by: Shalier Xia <shalierxia@microsoft.com>

docs: add resource requests and limits

---

CODEOWNERS

Matches the setting on the osm repo for code
approvals.

Update code owners to osm-approvers

---

content/docs/getting_started/cleanup.md
content/docs/guides/integrations/dapr.md
content/docs/guides/integrations/prometheus.md
content/docs/guides/troubleshooting/uninstall.md
content/docs/guides/uninstall.md

Resolves #249.
Signed-off-by: Johnson Shi <Johnson.Shi@microsoft.com>

docs(uninstall): add cluster-wide-resources uninstall docs

---

content/docs/guides/uninstall.md

Update uninstall doc

---

content/docs/guides/traffic_management/ingress.md

ingress: update guidance for ingress options

---

content/_index.md

docs(content/_index.md): improve content of main landing page

---

content/_index.md

docs(content/_index.md): fixed typo

---

content/docs/guides/observability/logs.md

[fix]: replace top level chart key OpenServiceMesh with osm

---

content/docs/guides/ha_scale/high_availability.md

Adds memory utilization to HPA section of HA guide
Signed-off-by: Shalier Xia <shalierxia@microsoft.com>

Updates HPA documentation

---

content/docs/demos/cert-manager_integration.md
content/docs/guides/certificates.md

Adds a demo for cert-manager certificate
provider.
Resolves #301

demos: add cert-manager demo

---

config.toml
netlify.toml

Updates config.toml and netlify.toml to add the release-v1.0
specific docs.

release-v1.0: update redirect and release menu

---

content/docs/guides/install.md

Fixes typo in spelling of reconciler

guides(install): fix spelling typo

---

config.toml

Updates the envoy version to v1.19.3 in config.toml.

website/config: update envoy version to v1.19.3

---

content/docs/guides/observability/metrics.md

Part of https://github.com/openservicemesh/osm/issues/4568

add XDS request metric

---

content/docs/guides/observability/metrics.md

Part of https://github.com/openservicemesh/osm/issues/4568

add common_name, type labels to XDS response metrics

---

content/docs/demos/circuit_breaking_mesh_external.md
content/docs/demos/circuit_breaking_mesh_internal.md
content/docs/guides/traffic_management/circuit_breaking.md

Adds circuit breaking demo for egress traffic.
Part of openservicemesh/osm#4500

docs/circuit-breaking: add egress demo

---

content/docs/releases/feature_lifecycle.md

Lists circuit breaking as a supported feature.

docs: list circuit breaking feature

---

config.toml

Signed-off-by: Sarah Christoff <sarah.christoff13@gmail.com>
🚨 Do not merge until issue #349  is resolved per the release doc

Release v1.1: Update Release Specific Docs

---

netlify.toml

Signed-off-by: Sarah Christoff <sarah.christoff13@gmail.com>

release-v1.1: update website redirect

---

content/docs/guides/observability/metrics.md

Part of https://github.com/openservicemesh/osm/issues/4568

add osm_events_queued metric

---

content/docs/guides/uninstall.md

Fixes reference to deletion of cluster-wide-resources
Need to cherry pick to v1.1 docs branch

uninstall: fix typo in uninstall command

---

content/docs/guides/troubleshooting/container_startup.md
content/docs/guides/troubleshooting/control_plane_error_codes.md
content/docs/guides/troubleshooting/grafana.md
content/docs/guides/troubleshooting/prometheus.md
content/docs/guides/troubleshooting/traffic_management/_index.md
content/docs/guides/troubleshooting/traffic_management/egress.md
content/docs/guides/troubleshooting/traffic_management/ingress.md
content/docs/guides/troubleshooting/traffic_management/iptables_redirection.md
content/docs/guides/troubleshooting/traffic_management/permissive_traffic_policy_mode.md
content/docs/guides/troubleshooting/uninstall.md

- Updates the titles and description of troubleshooting
guides to be consistent
- Drops the word "troubleshooting` from the title
displayed in the table of contents as these titles
appear within the "Troubleshooting" title already.
- Adds weights topics

docs/TSGs: make title and description consistent

---

content/docs/guides/troubleshooting/traffic_management/egress.md
content/docs/guides/troubleshooting/traffic_management/permissive_traffic_policy_mode.md

Updates the TSGs for permissive mode and egress
to leverage the `osm verify` command for
troubleshooting.

tsg: update permissive and egress TSGs

---

content/docs/api_reference/config/v1alpha2.md
content/docs/demos/statefulsets.md
content/docs/guides/mesh_config.md

Write docs for statefulset feature in v1.2

---

content/docs/demos/statefulsets.md

Signed-off-by: Keith Mattix II <keithmattix2@gmail.com>

Fix statefulset demo

---

content/docs/guides/observability/metrics.md

Documentation for https://github.com/openservicemesh/osm/pull/4773 which changes some of the field tags to decouple from certificate common name

add documentation for upcoming metric changes

---

content/docs/guides/observability/metrics.md

Part of https://github.com/openservicemesh/osm/issues/4568

add osm_reconciliation_total metric

---

.gitignore
config.toml
themes/dosmy/layouts/robots.txt

Generate sitemap for better SEO.
Resolves #352 
robots.txt works at https://deploy-preview-391--osm-docs.netlify.app/robots.txt
Signed-off-by: Allen Leigh <allenlsy@gmail.com>

generate sitemap

---

content/docs/guides/troubleshooting/container_lifecycle.md

This change adds the conclusions we came to regarding making Jobs finish
as expected in https://github.com/openservicemesh/osm/issues/2316

add shutdown caveat for Jobs in a mesh

---

config.toml
content/en/docs/releases/docs.md
netlify.toml

docs: update config.toml for v1.2

---

config.toml

Updated config.toml for v1.2 of the docs

docs: update for v1.2

---

config.toml

Show archive banner and fix top in all releases link

docs: enable archive banner and fix typo

---

themes/dosmy/assets/scss/main.scss
themes/dosmy/layouts/docs/baseof.html
themes/dosmy/layouts/partials/banner.html
themes/dosmy/layouts/partials/navbar.html

add style and html for previous version banner

docs: add styles for previous version banner

---

content/docs/guides/app_onboarding/namespaces.md

Backports https://github.com/openservicemesh/osm-docs/commit/767eba3c46187485642af295add973ed6808e23c to release-v1.0

[backport] cherry-pick 767eba3 to release-v1.0

---

content/en/docs/getting_started/traffic_policies.md

Signed-off-by: James Sturtevant <jstur@microsoft.com>

Fix typo in link

---

content/en/docs/getting_started/setup_osm.md
content/en/docs/getting_started/traffic_policies.md
content/en/docs/getting_started/traffic_split.md
manifests/apps/bookstore.yaml
manifests/split/traffic-split-50-50.yaml
manifests/split/traffic-split-v1.yaml
manifests/split/traffic-split-v2.yaml

Backports fixes to v1.2: 
- https://github.com/openservicemesh/osm-docs/commit/2a23d97fa3cc64972bc8794c009a785bd8a0f54b
- https://github.com/openservicemesh/osm-docs/commit/629454430a97a87df2caab68e3b9a8c61033029c
- https://github.com/openservicemesh/osm-docs/commit/0ac225b21e3c09248005a2c693ca48eaeccd6177

[backport]: demo fixes to v1.2

---

content/en/docs/api_reference/config/v1alpha2.md
content/en/docs/demos/egress_policy.md
content/en/docs/guides/app_onboarding/_index.md
content/en/docs/guides/traffic_management/egress.md
content/en/docs/guides/troubleshooting/traffic_management/egress.md

Updates EgressPolicy usage docs to reflect
changes to the behavior made in the osm repo.

docs: update EgressPolicy usage

---

content/en/docs/demos/statefulsets.md

Fixes an URL to not point to a preview build.

docs: fix incorrect URL

---

content/en/docs/demos/global_rate_limit_http.md

Updates the global rate limit demo to define the external rate limit policies in the ConfigMap at the beginning versus at every step in the demo. When the rate limit ConfigMap is updated at different stages in the demo, the timing of when the rate limit config is picked up by the RLS service is determined by when kubelet refreshes the ConfigMap changes onto the pods. This results in a non-deterministic demo experience.
With this change, similar to the e2e test, all the policies applicable to the RLS are applied at the
beginning, so that the demo experience is smoother and not driven by when kubelet syncs the ConfigMap changes onto the RLS pod.

docs/demo: define global rate limit policies at the beginning

---

content/en/docs/releases/feature_lifecycle.md

…ion details
Add policy details around how and when APIs may be deprecated or removed.
fixes #360

docs: add API deprecation details
