openservicemesh/osm-docs

content/docs/apidocs/policy/v1alpha1.md
Since OSM leverages client-go v1.20, use the same API
version for doc references to ensure the go client API objects
are compatible with the types referenced in the corresponding
API references.
=> apidocs: refer to k8s 1.20 for core types

content/docs/install/manual_demo/_index.md, content/docs/tasks_usage/observability/metrics.md, content/docs/tasks_usage/observability/metrics_manual_guide.md, content/docs/tasks_usage/observability/tracing.md, content/docs/tasks_usage/traffic_management/egress.md, content/docs/tasks_usage/traffic_management/ingress.md, content/docs/tasks_usage/traffic_management/iptables_redirection.md, content/docs/tasks_usage/traffic_management/permissive_traffic_policy_mode.md, content/docs/troubleshooting/observability/prometheus.md, content/docs/troubleshooting/observability/tracing.md, content/docs/troubleshooting/traffic/egress.md, content/docs/troubleshooting/traffic/ingress.md, content/docs/troubleshooting/traffic/iptables_redirection.md, content/docs/troubleshooting/traffic/permissive_traffic_policy_mode.md
openservicemesh/osm#2738 deprecated the usage of osm-config
ConfigMap for dynamic control plane config updates. The
osm-mesh-config MeshConfig custom resource is used to store
and serve dynamic config for the control plane.
This change updates the docs to reflect the above change.
Notably, it does the following:
- Updates documentation pertaining to the use of osm-config
ConfigMap for configs stored in the osm-mesh-config resource.
- Updates documentation pertaining to the use of the `osm mesh
upgrade` command to update such config. This is no longer
necessary to preserve values during an upgrade since the
MeshConfig resouce is not updated by OSM during an upgrade.
=> docs: deprecate usage of ConfigMap in favor of MeshConfig

content/docs/tasks_usage/traffic_management/demos/_index.md, content/docs/tasks_usage/traffic_management/demos/azure_application_gateway_ingress_demo.md, content/docs/tasks_usage/traffic_management/demos/egress_policy_demo.md, content/docs/tasks_usage/traffic_management/demos/gloo_edge_ingress_demo.md, content/docs/tasks_usage/traffic_management/egress.md, content/docs/tasks_usage/traffic_management/ingress.md
Adds documentation for using egress policies along
with a demo guide.
Also fixes a broken references in the ingress doc.
Part of openservicemesh/osm#3045
=> docs/traffic: document egress policies usage

config.toml, themes/dosmy/layouts/partials/navbar.html
This PR changes the url for the logo in the top left, pointing it at the OSM homepage instead of the Docs homepage.
Closes #6. 
Signed-off-by: flynnduism <dev@ronan.design>
=> docs(chore): change the logo url

content/docs/design_concepts/interfaces.md, content/docs/install/manual_demo/_index.md, content/docs/tasks_usage/observability/_index.md
Fixing broken links of interfaces page and removed double headers headers Observability and OSM Manual Demo Guide .
Signed-off-by: Atharva321 <atharvapatil19202@gmail.com>
=> Fixing Broken links and removing double headers

config.toml
As per #36, this PR introduces the version dropdown menu in order to include a link to the [v0.8 docs](https://release-v0-8.docs.openservicemesh.io/).
Signed-off-by: flynnduism <dev@ronan.design>
=> add version menu with link to 0.8.0

content/docs/install/manual_demo.md, content/docs/install/uninstallation_guide.md
Fixing a few small errors:
- That `aliases` directive has a typo and in any case is not needed. (Deferring the larger aliases cleanup, but might as well remove this one now.)
- Corrected minimum required k8s version
- Fixing one other minor typo
=> Fixing minor errors

content/docs/tasks_usage/traffic_management/demos/egress_policy_demo.md
Adds a note for server-first protocols to clarify
usage.
=> egress: add a note for server-first protocols

config.toml
The version documented in the v0.8 branch is v0.8.x, not v0.8.0.
=> Clarify version

README.md
Fixing the link to the docs and making the list easier to parse.
=> Fixing link and indentation

content/docs/install/uninstallation_guide.md
Ingress resources are owned by the user and not OSM. Uninstalling
OSM does not imply the ingress resources must be removed.
=> uninstall: remove unnecessary reference to ingress cleanup

content/docs/install/manual_demo.md
This was incorrectly left at an older version.
=> Correcting the version of the images used.

content/docs/install/manual_demo.md
The existing demo is broken because of incorrect
host header matching specified which prevents
bookbuyer from accessing the bookstore service.
The host header in the HTTP request includes
the port, but the spec was missing this. Since
the host header feature is not complete (see
openservicemesh/osm#2369) and this is unnecessary
for this demo, this change removes it.
The demo works as expected with SMI policies
with this fix.
Resolves openservicemesh/osm#3491
=> manual_demo: fix HTTP route policy

content/docs/tasks_usage/certificates.md
Thanks for the nice installation instructions!
This PR contains two very minor changes to installation instructions for `osm` with `cert-manager`, one to create a `Secret` with the correct key name and other to point at the right place in docs for `Issuer` configuration.
Signed-off-by: irbekrm <irbekrm@gmail.com>
=> Update cert-manager installation instructions

content/docs/osm_mesh_config.md
Signed-off-by: Allen Leigh <allenlsy@gmail.com>
Original sidecar initContainerImage name is `openservicemesh:envoy-alpine`, which is a mistake.
Related issue: #117
=> Fix sidecar initContainerImage name

content/docs/tasks/traffic_management/iptables_redirection.md
Documents inbound port exclusions for sidecar traffic
interception.
Required for openservicemesh/osm#3582
=> traffic/iptables: inbound port exclusions

README.md
This PR updates the site's readme, to explain how the `oldversion` options should be used in the site's `config.toml` file during the versioning process.
Addresses #128.
=> Update readme versioning

content/docs/tasks/traffic_management/ingress.md, content/docs/tasks/traffic_management/iptables_redirection.md
Backports cfeda91 and 2c2e3fa from main to release v0.9.
The features have been backported to osm/release-v0.9 branch
already.
=> Backport docs for port exclusion and ingress

content/docs/getting_started/manual_demo.md
v0.9.1 is the latest release. This change updates
the demo doc to point to the latest released version
on the release-v0.9 branch.
=> release/v0.9.1: update demo to v0.9.1

content/docs/tasks/traffic_management/ingress.md
The label value is a string, quote it so it doesn't
get interpreted as a boolean, which fails k8s API
validation.
=> ingress: fix label value

content/docs/tasks/traffic_management/ingress.md
The label value is a string, quote it so it doesn't
get interpreted as a boolean, which fails k8s API
validation.
=> [backport] ingress: fix label value

content/docs/concepts_features/osm_mesh_config.md, content/docs/install/_index.md, content/docs/tasks/observability/_index.md, content/docs/tasks/onboard_services.md, content/docs/tasks/traffic_management/_index.md, content/docs/tasks/traffic_management/egress.md, content/docs/tasks/traffic_management/troubleshooting/_index.md
- Fixes broken links and uses absolute paths to
avoid the broken links that arise from using
relative paths incorrectly
- Fixes typo in command
- Removes unnecessary aliases
Testing done:
- Verified the changes work as expected on the website preview
=> docs: fix broken links and use absolute paths

content/docs/tasks/observability/metrics.md
Because the backticks were not aligned, everything after this point in
the doc was formatted as raw markdown in a code block.
=> fix code block formatting

content/docs/tasks/onboard_services.md
Clarify ambiguity around application onboarding, and
remove references to code that does more than onboarding
namespaces, and observability references that are not
related to app onboarding.
=> docs: clarify application onboarding

content/docs/concepts_features/high_availability.md
Updates the HA doc, adding the horizontal pod autoscale and pod disruption budget sections
Signed-off-by: Shalier Xia <shalierxia@microsoft.com>
=> [backport]: cherry-pick a008d51 to release-v0.9

content/docs/demos/egress_policy.md
Drops the `demo` and period from the title to make it consistent
with other demo docs within the same section.
=> demos/egress_policy: make title and topic name consistent

content/docs/demos/egress_passthrough.md, content/docs/demos/egress_policy.md, content/docs/demos/ingress_contour_demo.md, content/docs/demos/outbound_ip_exclusion.md, content/docs/demos/permissive_traffic_mode.md, content/docs/demos/prometheus_grafana.md, content/docs/guides/traffic_management/egress.md, content/docs/guides/traffic_management/iptables_redirection.md, content/docs/guides/traffic_management/permissive_mode.md
- Consolidates the traffic management demos under `docs/demos`
- Removes the install step from demos to make it a prerequisite
- Removes hardcoded install namespace
=> traffic_management: reorganize demos

content/docs/demos/ingress_contour_demo.md
Fixes a typo in the HTTPS ingress section.
=> demos/ingress: fix typo

config.toml
Clarifies that the latest version tag on the website
refers to an unreleased version. Without this clarification,
users are misled to think the latest version is a released
version. Although there is a banner on the release specific
docs page, most users directly click on the "latest" version
without ever going to the release specific page.
=> config: clarify latest version tag on website

content/docs/getting_started/install.md
PSP support is being deprecated in OSM as it is being deprecated in Kubernetes. We will explore replacing it with [Pod Security Admission](https://kubernetes.io/docs/concepts/security/pod-security-admission/) in the future
Signed-off-by: Kalya Subramanian <kasubra@microsoft.com>
=> doc(psp): Deprecate PSP support

content/docs/getting_started/install.md, content/docs/getting_started/upgrade.md
This change clarifies that each version of the OSM CLI is only supported
when operating on the OSM chart with the same version.
Fixes #94
=> state CLI and chart version compatibility

content/docs/guides/observability/logs.md
This change adds information to the logging documentation about what
kinds of information users should and should not expect in logs and what
the verbosity levels are and what they mean.
Part of openservicemesh/osm#2924
=> logging: add details about verbosity and what's logged

README.md, config.toml, netlify.toml
Makes docs.openservicemesh.io point to the latest released version
and not unreleased version. Removes unreleased versions from the
site. Changes on main can instead be previewed using Netlify.
Updates docs for creating a release specific site.
Resolves #191.
=> Redirect docs.openservicemesh.io to point to latest version

config.toml, netlify.toml, themes/dosmy/layouts/partials/banner.html
Adds the v0.10 release specific branch to the version params and
updates the version banner to remove the reference to main. Adds
redirect to v0.10.
=> Update v0.8 for latest release v0.10

config.toml, netlify.toml, themes/dosmy/layouts/partials/banner.html
Adds the v0.10 release specific branch to the version params and
updates the version banner to remove the reference to main.
=> Update v0.9 for latest release v0.10

content/docs/getting_started/setup_osm.md, content/docs/getting_started/traffic_policies.md, content/docs/guides/traffic_management/permissive_mode.md, content/docs/guides/troubleshooting/traffic_management/permissive_traffic_policy_mode.md
Subtle language updates to indicate that permissive mode is specific to access control policies/traffic targets, not all SMI policies
ref: https://github.com/openservicemesh/osm/issues/2527 
=> update docs for traffic split in permissive mode

content/docs/demos/prometheus_grafana.md, content/docs/guides/observability/metrics.md
Creating PR for @jaellio
To avoid blocking v1 on uploading the Grafana dashboards to the
Grafana dashboard library, remove option from docs to get OSM
dashboards from the library. The dashboard JSON is still available
in the OSM repo. Instructions can be added back once the
dashboards for v1 have been added the OSM Grafana account.
=> Temporarily remove references to Grafana.com

content/docs/demos/ingress_contour.md, content/docs/demos/ingress_k8s_nginx.md, content/docs/guides/traffic_management/ingress.md
Clarifies that the targetPort must be specified in the
IngressBackend configuration.
Resolves openservicemesh/osm#4356
=> docs/ingress: clarify the port to specify in IngressBackend

content/docs/guides/app_onboarding/sidecar_injection.md
Clarifies that hostNetwork must not be set to true in the pod
spec for sidecar injection.
Part of openservicemesh/osm#4359
=> docs: clarify hostNetwork implication on sidecar injection

content/docs/guides/app_onboarding/app_protocol_selection.md
This change updates the doc explaining how to set `appProtocol` to match
changes made in https://github.com/openservicemesh/osm/pull/4325
- Remove references to naming the port name with the protocol, which is
no longer used.
- Add `tcp-server-first`
=> update app protocol docs

content/docs/guides/observability/metrics.md
Dashboard images correspond to dashboards in v1.0.0-rc.2.
Notable changes include the updates to latency graphs,
the addition of a workload to workload dashboard, and the
removal of the Max Envoy Update Time and Avg Envoy Update Time
graphs from the envoy details dashboard.
=> Update Grafana dashboards images

content/docs/releases/feature_lifecycle.md
Documents Helm chart value deprecation.
Resolves #openservicemesh/osm#2975
=> docs: document Helm values deprecation

content/docs/guides/_index.md, content/docs/guides/app_onboarding/_index.md, content/docs/guides/cli.md, content/docs/guides/install.md, content/docs/guides/osm_resource_limits.md, content/docs/guides/smi.md, content/docs/guides/uninstall.md, content/docs/guides/upgrade.md, themes/dosmy/layouts/partials/sidebar-tree.html
Change order and wording of doc titles in left nav for better
findability
docs(themes/dosmy/layouts/partials/sidebar-tree.html): change display
logic of left nav
Updated display logic to expand tree for active items only. This
allows for a cleaner display and makes it easier to navigate.
=> docs(content/docs/guides/*): update left nav order and titles

content/docs/guides/certificates.md
Updates the set option to `certificateProvider.kind`.
`certificateManager` is no longer a supported set option on osm
install.
=> fix(certificate): update certificateManager to certificateProvider

content/docs/api_reference/config/v1alpha1.md, content/docs/api_reference/policy/v1alpha1.md, content/docs/guides/traffic_management/ingress.md
Updates the API reference docs and clarifies the usage of
the different source kinds that can be specified in an
IngressBackend config.
Part of openservicemesh/osm#4391
=> docs: update api reference and add examples to ingress guide

content/docs/demos/ingress_k8s_nginx.md
The nginx ingress controller demo had a namespace of `ingress` but the Kubernetes nginx ingress controller installs in the `ingress-nginx` namespace. This PR fixes that in the documentation for a fully working demo.
=> Fix namespace for nginx ingress controller demo

content/docs/demos/ingress_contour.md
Clarifies the subject name used for backend TLS.
=> demos/ingress: clarify subject name usage

content/docs/guides/ha_scale/scale.md
Uses absolute paths to fix and avoid broken links.
The images are currently missing from the scale and
limit doc.
=> fix(scale): update image references in Scale and Limits doc

CODEOWNERS
Adds osm-docs-approvers as a code owner.
=> CODEOWNERS: add osm-docs-approvers

content/docs/guides/observability/tracing.md
Add documentation about propagating tracing headers from application
Signed-off-by: Allen Leigh <allenlsy@gmail.com>
=> docs(tracing): progagating tracing headers

content/docs/getting_started/observability.md, content/docs/guides/observability/metrics.md
Clarify in the observability section of the getting started guide
that metrics scraping must be enabled on a namespace for the
pods in that namespace to be annotated by the osm injector. Also
adds this clarification to the metrics how to guide intro section.
Removes an incorrect statement about pods needing to be recreated for
the annotations to be added or removed corresponding to
metrics being enabled or disabled on the namespace.
=> docs(metrics): clarify instructions for enabling metrics scraping

content/docs/getting_started/observability.md, content/docs/guides/observability/metrics.md
Backports c53b44d
---
Clarifies in the observability section of the getting started
guide that metrics scraping must be enabled on a namespace for the
pods in that namespace to be annotated by the osm injector. Also
adds this clarification to the metrics how to guide intro section.
Removes incorrect statement about pods needing to be recreated for
the annotations to be to added or removed corresponding to
metrics being enabled or disabled on the namespace.
=> [backport] docs(metrics): clarify instructions for enabling metrics scraping (#321)

config.toml, netlify.toml
frontport(?) of #234 since the site still seems to redirect to v0.11
=> release-v1.0: update redirect and release menu

content/docs/getting_started/install_apps.md, content/docs/getting_started/observability.md, content/docs/getting_started/setup_osm.md, content/docs/getting_started/traffic_policies.md, content/docs/getting_started/traffic_split.md
Adds "Next steps" sections to the getting started pages to help users navigate the manual demo. Since this was split into several different pages, some of the natural flow is missing
Ex: the end of the Deploy Sample Applications page currently leaves a reader in suspense
=> docs(demo): add links for logical flow of getting started section

content/docs/getting_started/cleanup.md, content/docs/guides/integrations/dapr.md, content/docs/guides/integrations/prometheus.md, content/docs/guides/troubleshooting/uninstall.md, content/docs/guides/uninstall.md
Updated docs to replace `osm uninstall cluster-wide-resoures` with `osm
uninstall mesh --delete-cluster-wide-resources`
part of https://github.com/openservicemesh/osm/issues/4429
=> use single uninstall command to delete cluster wide resources

content/docs/guides/app_onboarding/prereqs.md
* Documents security context requirements for applications
* Resolves https://github.com/openservicemesh/osm/issues/4388 and https://github.com/openservicemesh/osm/issues/4492
**Testing done:**
- `runAsNonRoot` requires `runAsUser` to be set: 
Omitting user ID causes the error `Error: container has runAsNonRoot and image will run as root` as seen here https://github.com/openservicemesh/osm/issues/4388
- No additional capabilities necessary:
Containers with the following security context dropping capabilities did not error -
```
capabilities:
drop:
- ALL
```
=> guides(app-onboarding): document app security context requirements

content/docs/guides/ha_scale/high_availability.md
Adds note to high availability docs about
affect of pod anti-affinities
=> guides(ha): add note about pod anti-affinities

content/docs/guides/app_onboarding/prereqs.md
Adds example of runAsNonRoot and runAsUser security contexts to app
onboarding prereqs
=> guides(app-onboarding): add example to security context prereqs

content/docs/guides/health_checks/health_probes.md, content/docs/guides/traffic_management/iptables_redirection.md
Updates tcpSocket probe docs to reflect changes made in [#4558](https://github.com/openservicemesh/osm/issues/4558).
Documents tcpSocket probe rewrite and osm-healthcheck.
Updates known issues to reference [#3773](https://github.com/openservicemesh/osm/issues/3773).
=> docs(health-checks): update tcpSocket probe support

config.toml, content/docs/demos/canary_rollout.md, content/docs/demos/cert-manager_integration.md, content/docs/demos/circuit_breaking_mesh_external.md, content/docs/demos/circuit_breaking_mesh_internal.md, content/docs/demos/egress_passthrough.md, content/docs/demos/egress_policy.md, content/docs/demos/ingress_contour.md, content/docs/demos/ingress_k8s_nginx.md, content/docs/demos/outbound_ip_exclusion.md, content/docs/demos/permissive_traffic_mode.md, content/docs/demos/prometheus_grafana.md, content/docs/demos/tcp_traffic_routing.md, content/docs/guides/cli.md, content/docs/guides/install.md
Updates the minimum required k8s version to v.20.0
to reflect the change made by commit 97c6395b in
as a part of openservicemesh/osm#4610.
=> docs: update minimum required k8s version to v1.20.0

content/docs/getting_started/install_apps.md
The docs site has the repo URL rendered automatically with the closing
parenthesis, breaking the link that is generated. This PR fixes that by
using a project link with text and the same repo URL. Fixes 
openservicemesh/osm#4674.
Signed-off-by: Thomas Stringer <thomas@trstringer.com>
=> Fix repo URL rendering

content/docs/getting_started/install_apps.md, content/docs/getting_started/observability.md, content/docs/getting_started/traffic_split.md
The existing port-forward-all.sh script in the code repo forwards ports
for the demo described here and the automated demo defined in the code
repo. The automated demo defines a `bookstore-v1` deployment where the
demo here names it only `bookstore`, both of which are port-forwarded by
the script, which then throws nondescript messages related to either one
of those not existing when running either demo.
These changes inline the specific scripts needed at each point in the
demo to ensure only components that are expected to exist have ports
forwarded so no error messages are expected.
Part of https://github.com/openservicemesh/osm/issues/3521
=> inline port-forward scripts in demo

content/docs/guides/troubleshooting/traffic_management/_index.md
index.md auto renders the table of contents,
remove redundant table.
=> tsg: remove duplicate table of contents

content/docs/demos/circuit_breaking_mesh_internal.md, content/docs/demos/retry_policy.md, content/docs/guides/traffic_management/retry_policy.md
Adds documentation and demo for retry policy and fixes typo
resolves https://github.com/openservicemesh/osm-docs/issues/318
=> Adds retry documentation and demo

content/docs/guides/certificates.md
Currently root cert rotation causes downtime between a users' services. We should warn them about this.
=> Add a warning about root cert rotation in its current state

content/docs/api_reference/policy/v1alpha1.md, content/docs/demos/local_rate_limit_connections.md, content/docs/guides/traffic_management/rate_limiting.md, manifests/samples/fortio/fortio-client.yaml, manifests/samples/fortio/fortio.yaml
Adds the guide and demo for local rate limiting
capability.
Currently, this is limited to L4 connection level
rate limiting, at par with OSM capability.
Adds and updates (uses named ports for protocol selection)
required demo manifests.
Part of openservicemesh/osm#2018
=> docs: add local rate limiting guide and demo

CONTRIBUTING.md, SUPPORT
Added GitHub support files, similar to the main repo, to help contributors.
=> docs: add GitHub support files for contributors

content/docs/guides/app_onboarding/namespaces.md
Adds note about restarting deployments in namespaces that are added to a mesh
=> namespace add: clarify sidecar injection for existing deployments

README.md, config.toml, content/docs/releases/docs.md, themes/dosmy/assets/scss/main.scss, themes/dosmy/layouts/docs/baseof.html, themes/dosmy/layouts/partials/banner.html, themes/dosmy/layouts/partials/navbar.html
- Updated style and HTML to always have previous versions banner available.
- Added toml config to disable by default. This can be changed to enable when newer release is available.
- Updated readme with correct instructions
=> docs: add banner and toggle config for previous versions

content/en/docs/getting_started/traffic_split.md, manifests/apps/bookstore-v2.yaml, manifests/apps/bookstore.yaml
This change updates the documentation to
reflect the change made to the traffic split
behavior in https://github.com/openservicemesh/osm/pull/4902.
=> traffic-split: update root service usage

content/en/docs/getting_started/traffic_split.md, manifests/apps/bookstore-v2.yaml, manifests/apps/bookstore.yaml
Backports 51d874e to release-v1.2
---
This change updates the documentation to
reflect the change made to the traffic split
behavior in https://github.com/openservicemesh/osm/pull/4902.
=> [backport] traffic-split: update root service usage (#413)

config.toml, content/en/docs/releases/docs.md, netlify.toml
add 1.2 release to dropdown and added redirect from main url to 1.2 docs
=> docs: update config.toml and netify.toml for 1.2

config.toml, themes/dosmy/assets/scss/main.scss, themes/dosmy/layouts/docs/baseof.html, themes/dosmy/layouts/partials/banner.html, themes/dosmy/layouts/partials/navbar.html
Updated release list to supported versions and redirect banner to latest release. This is consistent with https://github.com/openservicemesh/osm/pull/4853
=> docs: remove unsupported versions release list and update banner link

content/en/docs/getting_started/setup_osm.md
When following the install instructions at https://release-v1-2.docs.openservicemesh.io/docs/getting_started/setup_osm/#for-gnulinux-and-macos
I got the following on Ubuntu:
```
./${system}-amd64/osm version
-bash: ./Linux-amd64/osm: No such file or directory
```
The folder was `linux-amd64`.  This makes sure that the files are lowercased and should work on Mac's as well
=> Lowercase to support files system that aren't case sensitive

content/en/docs/getting_started/traffic_split.md, manifests/apps/bookstore.yaml, manifests/split/traffic-split-50-50.yaml, manifests/split/traffic-split-v1.yaml, manifests/split/traffic-split-v2.yaml
Signed-off-by: James Sturtevant <jstur@microsoft.com>
When running the demo at https://release-v1-2.docs.openservicemesh.io/docs/getting_started/traffic_split/#deploy-bookstore-v2-application even though the docs state: `The counter should not be incrementing because no traffic is flowing yet to the bookstore-v2 service.`
I was seeing traffic flow.  This was because the Kubernetes service was selecting all pods with the label `app: bookstore`  ~where as it should have been selecting just v1.~ as it was the root service.  
This is a follow up to https://github.com/openservicemesh/osm-docs/pull/413 where this change was initially made
=> demo: update the traffic split docs to meet expectations for root services

content/en/docs/demos/global_rate_limit_connections.md, content/en/docs/demos/local_rate_limit_connections.md, content/en/docs/demos/local_rate_limit_http.md
Adds global L4 rate limiting demo using an external
rate limit service.
This change documents the behavior in https://github.com/openservicemesh/osm/pull/4937
Part of openservicemesh/osm#2018
=> docs: add global L4 rate limiting demo

content/en/docs/api_reference/policy/v1alpha1.md, content/en/docs/demos/global_rate_limit_connections.md, content/en/docs/demos/global_rate_limit_http.md, content/en/docs/demos/local_rate_limit_connections.md, content/en/docs/demos/local_rate_limit_http.md, content/en/docs/guides/traffic_management/rate_limiting.md
- adds a demo guide for global rate limit of HTTP traffic
- updates existing rate limit docs for consistency
- updates API reference guide
Part of openservicemesh/osm#2018
=> docs/rate-limit: add global rate limit demo and docs

CONTRIBUTING.md, content/en/docs/getting_started/traffic_split.md
- Fixed broken links for `traffic_split` and `installation guide` in file `content/en/docs/getting_started/traffic_split.md`
- Correct directory name from `osm` to `osm-docs`
Signed-off-by: Wen Lin <linwen1991@gmail.com>
=> docs(typo): fixed broken links in traffic_split.md and correct typo in CONTRIBUTING.md

themes/dosmy/layouts/robots.txt
Signed-off-by: Zach Rhoads <zarhoads@microsoft.com>
Updated robots.txt to exclude the zh localization
=> docs: remove zh localization from search indexing

content/en/docs/api_reference/config/v1alpha2.md, content/en/docs/api_reference/policy/v1alpha1.md, content/en/docs/guides/observability/envoy_access_logs.md
Adds a guide describing Envoy access log
configuration. Also updates the API reference
docs.
Part of openservicemesh/osm#5136
=> docs: add envoy access log guide

content/en/docs/demos/certificate_rotation.md, content/en/docs/guides/certificate_management/_index.md, content/en/docs/guides/certificate_management/certificate-rotation.md, content/en/docs/guides/certificate_management/certificates.md
This adds documentation and demo for the MeshRootCertificate feature.  
Requires a few PR's in the OSM repo so a hold is on but would like to get feedback on the changes.
Resolves #436 
Resolves #434 
Signed-off-by: James Sturtevant <jstur@microsoft.com>
=> docs/demo: Add MeshRootCertificate information to docs

themes/dosmy/layouts/_default/_markup/render-link.html
After applying the localization feature, the link rendered in a non-default language page lost language code. For example, if we click the internal link on page https://release-v1-2.docs.openservicemesh.io/zh/, it will direct us to the English page.
To fix this, a markdown rendering link hook is involved in which using Hugo function [absLangURL](https://gohugo.io/functions/abslangurl/) will convert the link to the one with the correct language code.
BTW, the commit should be synced to the main branch too.
=> fix lang code lost in rendered link
